---
- name: Gestión de usuarios en servidores Unix/Linux
  hosts: linux_servers
  become: true
  gather_facts: true

  tasks:
    - name: Rol Parcheo CENTOS
      ansible.builtin.include_role:
        name: manage_users
