---
- name: Crear usuario en el sistema con contrase単a predeterminada
  ansible.builtin.user:
    name: "{{ manage_users_name }}"
    shell: "{{ manage_users_shell | default('/bin/bash') }}"
    home: "{{ manage_users_home | default('/home/' + manage_users_name) }}"
    password: "{{ manage_users_password | password_hash('sha512') }}" # Contrase単a predeterminada
    groups: "{{ manage_users_groups }}"
    state: present

- name: Crear el directorio home si no existe
  ansible.builtin.file:
    path: "{{ manage_users_home | default('/home/' + manage_users_name) }}"
    state: directory
    owner: "{{ manage_users_name }}"
    group: "{{ manage_users_groups.split(',')[0] }}" # Asignar grupo principal
    mode: "0755"

# Obligamos a cambiar la contrase単a en el primer login
- name: Obligar al usuario a cambiar la contrase単a al primer login
  ansible.builtin.command:
    cmd: "chage -d 0 {{ manage_users_name }}"
  changed_when: true
